[package]
name = "server"
version = "0.0.0"
description = "Top-level server response handling"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/server.rs"
doctest = false
test = false

[dependencies]
anyhow = { features = ["backtrace"], version = "1.0.75" }
dashmap = "5.4.0"
concurrent-queue = "2.2.0"
enum-iterator = "1.3.0"
once_cell = "1.17.1"
serde_json = "1.0.93"
serde = { version = "1.0.152", features = ["derive"] }
sled = "0.34.7"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-stream = "0.1.12"
tonic = "0.8.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
ulid = "1.0.0"

actions = { path = "../actions", version = "0.0.0" }
adapters = { path = "../adapters", version = "0.0.0" }
adventure_actions = { path = "../adventure/adventure_actions", version = "0.0.0" }
adventure_data = { path = "../data/adventure_data", version = "0.0.0" }
adventure_display = { path = "../adventure/adventure_display", version = "0.0.0" }
adventure_generator = { path = "../adventure/adventure_generator", version = "0.0.0" }
ai_core = { path = "../ai/ai_core", version = "0.0.0" }
ai_game_integration = { path = "../ai/ai_game_integration", version = "0.0.0" }
core_data = { path = "../data/core_data", version = "0.0.0" }
core_ui = { path = "../core_ui", version = "0.0.0" }
database = { path = "../database", version = "0.0.0" }
deck_editor = { path = "../deck_editor", version = "0.0.0" }
decklists = { path = "../decklists", version = "0.0.0" }
display = { path = "../display", version = "0.0.0" }
game_data = { path = "../data/game_data", version = "0.0.0" }
game_tables = { path = "../game_tables", version = "0.0.0" }
panel_address = { path = "../panel_address", version = "0.0.0" }
panels = { path = "../panels", version = "0.0.0" }
player_data = { path = "../data/player_data", version = "0.0.0" }
protos = { path = "../protos", version = "0.0.0" }
routing = { path = "../routing", version = "0.0.0" }
rules = { path = "../rules", version = "0.0.0" }
screen_overlay = { path = "../screen_overlay", version = "0.0.0" }
tutorial = { path = "../tutorial", version = "0.0.0" }
user_action_data = { path = "../data/user_action_data", version = "0.0.0" }
with_error = { path = "../with_error", version = "0.0.0" }
