[package]
name = "rules"
version = "0.0.0"
description = "All game rules, card definitions, and associated helpers"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/rules.rs"
test = false
doctest = false

[dependencies]
card_definition_data = { path = "../data/card_definition_data", version = "0.0.0" }
constants = { path = "../constants", version = "0.0.0" }
core_data = { path = "../data/core_data", version = "0.0.0" }
dispatcher = { path = "../dispatcher", version = "0.0.0" }
game_data = { path = "../data/game_data", version = "0.0.0" }
with_error = { path = "../with_error", version = "0.0.0" }

anyhow = { features = ["backtrace"], version = "1.0.75" }
dashmap = "5.4.0"
enum-iterator = "1.3.0"
once_cell = "1.17.1"
tracing = "0.1.37"
