[package]
name = "rules"
version = "0.0.0"
description = "All game rules, card definitions, and associated helpers"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/rules.rs"
test = false
doctest = false

[dependencies]
constants = { path = "../constants", version = "0.0.0" }
game_data = { path = "../data/game_data", version = "0.0.0" }
with_error = { path = "../with_error", version = "0.0.0" }

anyhow = "1.0.58"
dashmap = "5.3.4"
enum-iterator = "1.1.3"
once_cell = "1.13.0"
tracing = { version = "0.1.35", features = ["max_level_debug", "release_max_level_warn"] }
