[package]
name = "adventure_actions"
version = "0.0.0"
description = "Implements game rules for the 'adventure' deckbuilding/drafting game mode"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/adventure_actions.rs"
test = false
doctest = false

[dependencies]
anyhow = "1.0.58"

adventure_data = { path = "../../data/adventure_data", version = "0.0.0" }
adventure_generator = { path = "../adventure_generator", version = "0.0.0" }
core_data = { path = "../../data/core_data", version = "0.0.0" }
game_data = { path = "../../data/game_data", version = "0.0.0" }
player_data = { path = "../../data/player_data", version = "0.0.0" }
rules = { path = "../../rules", version = "0.0.0" }
with_error = { path = "../../with_error", version = "0.0.0" }
