[package]
name = "cards_all"
version = "0.0.0"
description = "All known cards & associated helpers"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/cards_all.rs"
test = false
doctest = false

[build-dependencies]
anyhow = { features = ["backtrace"], version = "1.0.75" }
regex = "1.7.1"
walkdir = "2.3.2"

[dependencies]
cards_amethyst = { path = "../cards_amethyst", version = "0.0.0" }
cards_basic = { path = "../cards_basic", version = "0.0.0" }
cards_beryl = { path = "../cards_beryl", version = "0.0.0" }
cards_game_modifier = { path = "../cards_game_modifier", version = "0.0.0" }
cards_test = { path = "../cards_test", version = "0.0.0" }
rules = { path = "../../rules", version = "0.0.0" }
