[package]
name = "tutorial"
version = "0.0.0"
homepage = "https://github.com/thurn/riftcaller"
description = "Tutorial for how to play the game"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/tutorial.rs"
test = false
doctest = false

[dependencies]
actions = { path = "../actions", version = "0.0.0" }
core_ui = { path = "../core_ui", version = "0.0.0" }
card_definition_data = { path = "../data/card_definition_data", version = "0.0.0" }
game_data = { path = "../data/game_data", version = "0.0.0" }
core_data = { path = "../data/core_data", version = "0.0.0" }
raid_display = { path = "../raid_display", version = "0.0.0" }
rules = { path = "../rules", version = "0.0.0" }
with_error = { path = "../with_error", version = "0.0.0" }

anyhow = { features = ["backtrace"], version = "1.0.75" }
once_cell = "1.17.1"
tracing = "0.1.37"
