steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', "--build-arg", "SDVERSION=$SHORT_SHA", '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/spelldawn/spelldawn:$COMMIT_SHA', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/spelldawn:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
   - 'run'
   - 'deploy'
   - 'spelldawn'
   - '--image'
   - 'gcr.io/$PROJECT_ID/spelldawn:$COMMIT_SHA'
   - '--region'
   - 'us-central1'

images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/spelldawn/spelldawn:$COMMIT_SHA'
