[package]
name = "ai_testing"
version = "0.0.0"
description = "Tools for testing AI implementations"
license = "Apache-2.0"
edition = "2021"

[lib]
doctest = false
test = false

[[bin]]
name = "run_nim"
path = "scripts/run_nim.rs"
test = false

[[bin]]
name = "run_matchup"
path = "scripts/run_matchup.rs"
test = false

[dependencies]
ai_core = { path = "../ai_core", version = "0.0.0" }
ai_game_integration = { path = "../ai_game_integration", version = "0.0.0" }
ai_monte_carlo = { path = "../ai_monte_carlo", version = "0.0.0" }
ai_tree_search = { path = "../ai_tree_search", version = "0.0.0" }
cards_all = { path = "../../cards/cards_all", version = "0.0.0" }
dispatcher = { path = "../../dispatcher", version = "0.0.0" }
game_data = { path = "../../data/game_data", version = "0.0.0" }
core_data = { path = "../../data/core_data", version = "0.0.0" }
decklists = { path = "../../decklists", version = "0.0.0" }
rules = { path = "../../rules", version = "0.0.0" }
with_error = { path = "../../with_error", version = "0.0.0" }

anyhow = "1.0.58"
clap = {version = "3.2.16", features = ["derive"]}

