[package]
name = "raids"
version = "0.0.0"
description = "Implements state machine model for handling raids"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/raids.rs"
test = false
doctest = false

[dependencies]
game_data = { path = "../data/game_data", version = "0.0.0" }
rules = { path = "../rules", version = "0.0.0" }
with_error = { path = "../with_error", version = "0.0.0" }

anyhow = { features = ["backtrace"], version = "1.0.75" }
fallible-iterator = "0.2.0"
tracing = "0.1.37"
