[package]
name = "riftcaller"
version = "0.0.0"
homepage = "https://github.com/thurn/riftcaller"
description = "Riftcaller: An asymmetric trading card game"
license = "Apache-2.0"
default-run = "riftcaller"
edition = "2021"

[[bin]]
name = "riftcaller"
path = "src/main.rs"
test = false
doctest = false

[dependencies]
cards_all = { path = "../cards/cards_all", version = "0.0.0" }
database = { path = "../database", version = "0.0.0" }
logging = { path = "../logging", version = "0.0.0", features = ["ansi"] }
protos = { path = "../protos", version = "0.0.0" }
server = { path = "../server", version = "0.0.0" }

tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
tonic = { version = "0.8.3", features = ["gzip"] }
tonic-web = "0.5.0"
tracing = { version = "0.1.37", features = ["max_level_debug"] }

[dev-dependencies]
rusty-hook = "0.11.2"
