[package]
name = "adventure_generator"
version = "0.0.0"
description = "Generates world maps for the 'adventure' game mode"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/adventure_generator.rs"
test = false
doctest = false

[dependencies]

game_data = { path = "../../data/game_data", version = "0.0.0" }
decklists = { path = "../../decklists", version = "0.0.0" }
rules = { path = "../../rules", version = "0.0.0" }
