[package]
name = "adventure_generator"
version = "0.0.0"
description = "Generates world maps for the 'adventure' game mode"
license = "Apache-2.0"
edition = "2021"

[lib]
test = false
doctest = false

[dependencies]
adventure_data = { path = "../../data/adventure_data", version = "0.0.0" }
card_definition_data = { path = "../../data/card_definition_data", version = "0.0.0" }
core_data = { path = "../../data/core_data", version = "0.0.0" }
decklists = { path = "../../decklists", version = "0.0.0" }
game_data = { path = "../../data/game_data", version = "0.0.0" }
game_tables = { path = "../../game_tables", version = "0.0.0" }

enumset = { version = "1.1.3", features = ["serde"] }