[package]
name = "constants"
version = "0.0.0"
description = "Numerical constants for UI rendering & gameplay"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/constants.rs"
doctest = false
test = false
