[package]
name = "cards_test"
version = "0.0.0"
description = "Test cards"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/lib.rs"
test = false
doctest = false

[dependencies]
card_helpers = { path = "../../card_helpers", version = "0.0.0" }
test_constants = { path = "../../test_constants", version = "0.0.0" }
card_definition_data = { path = "../../data/card_definition_data", version = "0.0.0" }
game_data = { path = "../../data/game_data", version = "0.0.0" }
core_data = { path = "../../data/core_data", version = "0.0.0" }
rules = { path = "../../rules", version = "0.0.0" }
