[package]
name = "cards_basic"
version = "0.0.0"
description = "Standard cards for tutorials and the adventure-mode starting decks"
license = "Apache-2.0"
edition = "2021"

[lib]
test = false
doctest = false

[dependencies]
assets = { path = "../../assets", version = "0.0.0" }
card_helpers = { path = "../../card_helpers", version = "0.0.0" }
game_data = { path = "../../data/game_data", version = "0.0.0" }
core_data = { path = "../../data/core_data", version = "0.0.0" }
rules = { path = "../../rules", version = "0.0.0" }
