[package]
name = "rules_text"
version = "0.0.0"
description = "Builds the text displayed on cards based on their card definition"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/rules_text.rs"
doctest = false
test = false

[dependencies]
assets = { path = "../assets", version = "0.0.0" }
dispatcher = { path = "../dispatcher", version = "0.0.0" }
rules = { path = "../rules", version = "0.0.0" }
card_definition_data = { path = "../data/card_definition_data", version = "0.0.0" }
game_data = { path = "../data/game_data", version = "0.0.0" }
core_data = { path = "../data/core_data", version = "0.0.0" }
protos = { path = "../protos", version = "0.0.0" }
core_ui = { path = "../core_ui", version = "0.0.0"}

convert_case = "0.5.0"