[package]
name = "routing"
version = "0.0.0"
description = "Handles turning a panel address into a panel implementation"
license = "Apache-2.0"
edition = "2021"

[lib]
path = "src/routing.rs"
test = false
doctest = false

[dependencies]
adventure_display = { path = "../adventure/adventure_display", version = "0.0.0" }
adventure_data = { path = "../data/adventure_data", version = "0.0.0" }
game_data = { path = "../data/game_data", version = "0.0.0" }
player_data = { path = "../data/player_data", version = "0.0.0" }
deck_editor = { path = "../deck_editor", version = "0.0.0" }
panel_address = { path = "../panel_address", version = "0.0.0" }
panels = { path = "../panels", version = "0.0.0" }

anyhow = { features = ["backtrace"], version = "1.0.75" }
protos = { path = "../protos", version = "0.0.0" }
serde_json = "1.0.93"
with_error = { path = "../with_error", version = "0.0.0" }
